; Auto-generated. Do not edit!


(cl:in-package pr_control_msgs-msg)


;//! \htmlinclude JointModeCommandFeedback.msg.html

(cl:defclass <JointModeCommandFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass JointModeCommandFeedback (<JointModeCommandFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <JointModeCommandFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'JointModeCommandFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name pr_control_msgs-msg:<JointModeCommandFeedback> is deprecated: use pr_control_msgs-msg:JointModeCommandFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <JointModeCommandFeedback>) ostream)
  "Serializes a message object of type '<JointModeCommandFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <JointModeCommandFeedback>) istream)
  "Deserializes a message object of type '<JointModeCommandFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<JointModeCommandFeedback>)))
  "Returns string type for a message object of type '<JointModeCommandFeedback>"
  "pr_control_msgs/JointModeCommandFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'JointModeCommandFeedback)))
  "Returns string type for a message object of type 'JointModeCommandFeedback"
  "pr_control_msgs/JointModeCommandFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<JointModeCommandFeedback>)))
  "Returns md5sum for a message object of type '<JointModeCommandFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'JointModeCommandFeedback)))
  "Returns md5sum for a message object of type 'JointModeCommandFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<JointModeCommandFeedback>)))
  "Returns full string definition for message of type '<JointModeCommandFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%# no feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'JointModeCommandFeedback)))
  "Returns full string definition for message of type 'JointModeCommandFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%# no feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <JointModeCommandFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <JointModeCommandFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'JointModeCommandFeedback
))
