; Auto-generated. Do not edit!


(cl:in-package pr_control_msgs-msg)


;//! \htmlinclude SetForceTorqueThresholdFeedback.msg.html

(cl:defclass <SetForceTorqueThresholdFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass SetForceTorqueThresholdFeedback (<SetForceTorqueThresholdFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SetForceTorqueThresholdFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SetForceTorqueThresholdFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name pr_control_msgs-msg:<SetForceTorqueThresholdFeedback> is deprecated: use pr_control_msgs-msg:SetForceTorqueThresholdFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SetForceTorqueThresholdFeedback>) ostream)
  "Serializes a message object of type '<SetForceTorqueThresholdFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SetForceTorqueThresholdFeedback>) istream)
  "Deserializes a message object of type '<SetForceTorqueThresholdFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SetForceTorqueThresholdFeedback>)))
  "Returns string type for a message object of type '<SetForceTorqueThresholdFeedback>"
  "pr_control_msgs/SetForceTorqueThresholdFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SetForceTorqueThresholdFeedback)))
  "Returns string type for a message object of type 'SetForceTorqueThresholdFeedback"
  "pr_control_msgs/SetForceTorqueThresholdFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SetForceTorqueThresholdFeedback>)))
  "Returns md5sum for a message object of type '<SetForceTorqueThresholdFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SetForceTorqueThresholdFeedback)))
  "Returns md5sum for a message object of type 'SetForceTorqueThresholdFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SetForceTorqueThresholdFeedback>)))
  "Returns full string definition for message of type '<SetForceTorqueThresholdFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# no feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SetForceTorqueThresholdFeedback)))
  "Returns full string definition for message of type 'SetForceTorqueThresholdFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# no feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SetForceTorqueThresholdFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SetForceTorqueThresholdFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'SetForceTorqueThresholdFeedback
))
