; Auto-generated. Do not edit!


(cl:in-package pr_control_msgs-msg)


;//! \htmlinclude SetPositionFeedback.msg.html

(cl:defclass <SetPositionFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass SetPositionFeedback (<SetPositionFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SetPositionFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SetPositionFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name pr_control_msgs-msg:<SetPositionFeedback> is deprecated: use pr_control_msgs-msg:SetPositionFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SetPositionFeedback>) ostream)
  "Serializes a message object of type '<SetPositionFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SetPositionFeedback>) istream)
  "Deserializes a message object of type '<SetPositionFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SetPositionFeedback>)))
  "Returns string type for a message object of type '<SetPositionFeedback>"
  "pr_control_msgs/SetPositionFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SetPositionFeedback)))
  "Returns string type for a message object of type 'SetPositionFeedback"
  "pr_control_msgs/SetPositionFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SetPositionFeedback>)))
  "Returns md5sum for a message object of type '<SetPositionFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SetPositionFeedback)))
  "Returns md5sum for a message object of type 'SetPositionFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SetPositionFeedback>)))
  "Returns full string definition for message of type '<SetPositionFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# no feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SetPositionFeedback)))
  "Returns full string definition for message of type 'SetPositionFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# no feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SetPositionFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SetPositionFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'SetPositionFeedback
))
