; Auto-generated. Do not edit!


(cl:in-package pr_control_msgs-msg)


;//! \htmlinclude TriggerFeedback.msg.html

(cl:defclass <TriggerFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass TriggerFeedback (<TriggerFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TriggerFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TriggerFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name pr_control_msgs-msg:<TriggerFeedback> is deprecated: use pr_control_msgs-msg:TriggerFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TriggerFeedback>) ostream)
  "Serializes a message object of type '<TriggerFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TriggerFeedback>) istream)
  "Deserializes a message object of type '<TriggerFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TriggerFeedback>)))
  "Returns string type for a message object of type '<TriggerFeedback>"
  "pr_control_msgs/TriggerFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TriggerFeedback)))
  "Returns string type for a message object of type 'TriggerFeedback"
  "pr_control_msgs/TriggerFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TriggerFeedback>)))
  "Returns md5sum for a message object of type '<TriggerFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TriggerFeedback)))
  "Returns md5sum for a message object of type 'TriggerFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TriggerFeedback>)))
  "Returns full string definition for message of type '<TriggerFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# no feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TriggerFeedback)))
  "Returns full string definition for message of type 'TriggerFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# no feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TriggerFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TriggerFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'TriggerFeedback
))
