// Generated by gencpp from file pr_control_msgs/JointGroupCommandGoal.msg
// DO NOT EDIT!


#ifndef PR_CONTROL_MSGS_MESSAGE_JOINTGROUPCOMMANDGOAL_H
#define PR_CONTROL_MSGS_MESSAGE_JOINTGROUPCOMMANDGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <trajectory_msgs/JointTrajectoryPoint.h>

namespace pr_control_msgs
{
template <class ContainerAllocator>
struct JointGroupCommandGoal_
{
  typedef JointGroupCommandGoal_<ContainerAllocator> Type;

  JointGroupCommandGoal_()
    : header()
    , joint_names()
    , command()  {
    }
  JointGroupCommandGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , joint_names(_alloc)
    , command(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _joint_names_type;
  _joint_names_type joint_names;

   typedef  ::trajectory_msgs::JointTrajectoryPoint_<ContainerAllocator>  _command_type;
  _command_type command;





  typedef boost::shared_ptr< ::pr_control_msgs::JointGroupCommandGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pr_control_msgs::JointGroupCommandGoal_<ContainerAllocator> const> ConstPtr;

}; // struct JointGroupCommandGoal_

typedef ::pr_control_msgs::JointGroupCommandGoal_<std::allocator<void> > JointGroupCommandGoal;

typedef boost::shared_ptr< ::pr_control_msgs::JointGroupCommandGoal > JointGroupCommandGoalPtr;
typedef boost::shared_ptr< ::pr_control_msgs::JointGroupCommandGoal const> JointGroupCommandGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pr_control_msgs::JointGroupCommandGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pr_control_msgs::JointGroupCommandGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pr_control_msgs::JointGroupCommandGoal_<ContainerAllocator1> & lhs, const ::pr_control_msgs::JointGroupCommandGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.joint_names == rhs.joint_names &&
    lhs.command == rhs.command;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pr_control_msgs::JointGroupCommandGoal_<ContainerAllocator1> & lhs, const ::pr_control_msgs::JointGroupCommandGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pr_control_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pr_control_msgs::JointGroupCommandGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pr_control_msgs::JointGroupCommandGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pr_control_msgs::JointGroupCommandGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pr_control_msgs::JointGroupCommandGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pr_control_msgs::JointGroupCommandGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pr_control_msgs::JointGroupCommandGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pr_control_msgs::JointGroupCommandGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "869c154392175f5d02b54e7c3c317c59";
  }

  static const char* value(const ::pr_control_msgs::JointGroupCommandGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x869c154392175f5dULL;
  static const uint64_t static_value2 = 0x02b54e7c3c317c59ULL;
};

template<class ContainerAllocator>
struct DataType< ::pr_control_msgs::JointGroupCommandGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pr_control_msgs/JointGroupCommandGoal";
  }

  static const char* value(const ::pr_control_msgs::JointGroupCommandGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pr_control_msgs::JointGroupCommandGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Used in time-stamping the goal.\n"
"Header header\n"
"\n"
"# Name list of the joints. You don't need to specify all joints of the\n"
"# robot. Joint names are case-sensitive.\n"
"string[] joint_names\n"
"\n"
"# A command to the joints listed in joint_names.\n"
"# Can be position, velocity, effort, and/or acceleration.\n"
"# The order must be identical.\n"
"# time_from_start is the command duration / timeout\n"
"# Set to 0 for no timeout.\n"
"trajectory_msgs/JointTrajectoryPoint command\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: trajectory_msgs/JointTrajectoryPoint\n"
"# Each trajectory point specifies either positions[, velocities[, accelerations]]\n"
"# or positions[, effort] for the trajectory to be executed.\n"
"# All specified values are in the same order as the joint names in JointTrajectory.msg\n"
"\n"
"float64[] positions\n"
"float64[] velocities\n"
"float64[] accelerations\n"
"float64[] effort\n"
"duration time_from_start\n"
;
  }

  static const char* value(const ::pr_control_msgs::JointGroupCommandGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pr_control_msgs::JointGroupCommandGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.joint_names);
      stream.next(m.command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointGroupCommandGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pr_control_msgs::JointGroupCommandGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pr_control_msgs::JointGroupCommandGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "joint_names[]" << std::endl;
    for (size_t i = 0; i < v.joint_names.size(); ++i)
    {
      s << indent << "  joint_names[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.joint_names[i]);
    }
    s << indent << "command: ";
    s << std::endl;
    Printer< ::trajectory_msgs::JointTrajectoryPoint_<ContainerAllocator> >::stream(s, indent + "  ", v.command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PR_CONTROL_MSGS_MESSAGE_JOINTGROUPCOMMANDGOAL_H
