// Generated by gencpp from file pr_control_msgs/JointGroupCommandActionGoal.msg
// DO NOT EDIT!


#ifndef PR_CONTROL_MSGS_MESSAGE_JOINTGROUPCOMMANDACTIONGOAL_H
#define PR_CONTROL_MSGS_MESSAGE_JOINTGROUPCOMMANDACTIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <pr_control_msgs/JointGroupCommandGoal.h>

namespace pr_control_msgs
{
template <class ContainerAllocator>
struct JointGroupCommandActionGoal_
{
  typedef JointGroupCommandActionGoal_<ContainerAllocator> Type;

  JointGroupCommandActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  JointGroupCommandActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::pr_control_msgs::JointGroupCommandGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::pr_control_msgs::JointGroupCommandActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pr_control_msgs::JointGroupCommandActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct JointGroupCommandActionGoal_

typedef ::pr_control_msgs::JointGroupCommandActionGoal_<std::allocator<void> > JointGroupCommandActionGoal;

typedef boost::shared_ptr< ::pr_control_msgs::JointGroupCommandActionGoal > JointGroupCommandActionGoalPtr;
typedef boost::shared_ptr< ::pr_control_msgs::JointGroupCommandActionGoal const> JointGroupCommandActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pr_control_msgs::JointGroupCommandActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pr_control_msgs::JointGroupCommandActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pr_control_msgs::JointGroupCommandActionGoal_<ContainerAllocator1> & lhs, const ::pr_control_msgs::JointGroupCommandActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pr_control_msgs::JointGroupCommandActionGoal_<ContainerAllocator1> & lhs, const ::pr_control_msgs::JointGroupCommandActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pr_control_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pr_control_msgs::JointGroupCommandActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pr_control_msgs::JointGroupCommandActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pr_control_msgs::JointGroupCommandActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pr_control_msgs::JointGroupCommandActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pr_control_msgs::JointGroupCommandActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pr_control_msgs::JointGroupCommandActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pr_control_msgs::JointGroupCommandActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "98542e4680653df086cf9a55dfcfaaac";
  }

  static const char* value(const ::pr_control_msgs::JointGroupCommandActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x98542e4680653df0ULL;
  static const uint64_t static_value2 = 0x86cf9a55dfcfaaacULL;
};

template<class ContainerAllocator>
struct DataType< ::pr_control_msgs::JointGroupCommandActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pr_control_msgs/JointGroupCommandActionGoal";
  }

  static const char* value(const ::pr_control_msgs::JointGroupCommandActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pr_control_msgs::JointGroupCommandActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"JointGroupCommandGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: pr_control_msgs/JointGroupCommandGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Used in time-stamping the goal.\n"
"Header header\n"
"\n"
"# Name list of the joints. You don't need to specify all joints of the\n"
"# robot. Joint names are case-sensitive.\n"
"string[] joint_names\n"
"\n"
"# A command to the joints listed in joint_names.\n"
"# Can be position, velocity, effort, and/or acceleration.\n"
"# The order must be identical.\n"
"# time_from_start is the command duration / timeout\n"
"# Set to 0 for no timeout.\n"
"trajectory_msgs/JointTrajectoryPoint command\n"
"\n"
"\n"
"================================================================================\n"
"MSG: trajectory_msgs/JointTrajectoryPoint\n"
"# Each trajectory point specifies either positions[, velocities[, accelerations]]\n"
"# or positions[, effort] for the trajectory to be executed.\n"
"# All specified values are in the same order as the joint names in JointTrajectory.msg\n"
"\n"
"float64[] positions\n"
"float64[] velocities\n"
"float64[] accelerations\n"
"float64[] effort\n"
"duration time_from_start\n"
;
  }

  static const char* value(const ::pr_control_msgs::JointGroupCommandActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pr_control_msgs::JointGroupCommandActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointGroupCommandActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pr_control_msgs::JointGroupCommandActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pr_control_msgs::JointGroupCommandActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::pr_control_msgs::JointGroupCommandGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PR_CONTROL_MSGS_MESSAGE_JOINTGROUPCOMMANDACTIONGOAL_H
