// Generated by gencpp from file pr_control_msgs/JointGroupCommandFeedback.msg
// DO NOT EDIT!


#ifndef PR_CONTROL_MSGS_MESSAGE_JOINTGROUPCOMMANDFEEDBACK_H
#define PR_CONTROL_MSGS_MESSAGE_JOINTGROUPCOMMANDFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <trajectory_msgs/JointTrajectoryPoint.h>
#include <trajectory_msgs/JointTrajectoryPoint.h>

namespace pr_control_msgs
{
template <class ContainerAllocator>
struct JointGroupCommandFeedback_
{
  typedef JointGroupCommandFeedback_<ContainerAllocator> Type;

  JointGroupCommandFeedback_()
    : header()
    , joint_names()
    , desired()
    , actual()  {
    }
  JointGroupCommandFeedback_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , joint_names(_alloc)
    , desired(_alloc)
    , actual(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _joint_names_type;
  _joint_names_type joint_names;

   typedef  ::trajectory_msgs::JointTrajectoryPoint_<ContainerAllocator>  _desired_type;
  _desired_type desired;

   typedef  ::trajectory_msgs::JointTrajectoryPoint_<ContainerAllocator>  _actual_type;
  _actual_type actual;





  typedef boost::shared_ptr< ::pr_control_msgs::JointGroupCommandFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pr_control_msgs::JointGroupCommandFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct JointGroupCommandFeedback_

typedef ::pr_control_msgs::JointGroupCommandFeedback_<std::allocator<void> > JointGroupCommandFeedback;

typedef boost::shared_ptr< ::pr_control_msgs::JointGroupCommandFeedback > JointGroupCommandFeedbackPtr;
typedef boost::shared_ptr< ::pr_control_msgs::JointGroupCommandFeedback const> JointGroupCommandFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pr_control_msgs::JointGroupCommandFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pr_control_msgs::JointGroupCommandFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pr_control_msgs::JointGroupCommandFeedback_<ContainerAllocator1> & lhs, const ::pr_control_msgs::JointGroupCommandFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.joint_names == rhs.joint_names &&
    lhs.desired == rhs.desired &&
    lhs.actual == rhs.actual;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pr_control_msgs::JointGroupCommandFeedback_<ContainerAllocator1> & lhs, const ::pr_control_msgs::JointGroupCommandFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pr_control_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pr_control_msgs::JointGroupCommandFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pr_control_msgs::JointGroupCommandFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pr_control_msgs::JointGroupCommandFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pr_control_msgs::JointGroupCommandFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pr_control_msgs::JointGroupCommandFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pr_control_msgs::JointGroupCommandFeedback_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pr_control_msgs::JointGroupCommandFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1a41b9418bc88d43721c4db353e5e3a8";
  }

  static const char* value(const ::pr_control_msgs::JointGroupCommandFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1a41b9418bc88d43ULL;
  static const uint64_t static_value2 = 0x721c4db353e5e3a8ULL;
};

template<class ContainerAllocator>
struct DataType< ::pr_control_msgs::JointGroupCommandFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pr_control_msgs/JointGroupCommandFeedback";
  }

  static const char* value(const ::pr_control_msgs::JointGroupCommandFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pr_control_msgs::JointGroupCommandFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"Header header\n"
"string[] joint_names\n"
"trajectory_msgs/JointTrajectoryPoint desired\n"
"trajectory_msgs/JointTrajectoryPoint actual\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: trajectory_msgs/JointTrajectoryPoint\n"
"# Each trajectory point specifies either positions[, velocities[, accelerations]]\n"
"# or positions[, effort] for the trajectory to be executed.\n"
"# All specified values are in the same order as the joint names in JointTrajectory.msg\n"
"\n"
"float64[] positions\n"
"float64[] velocities\n"
"float64[] accelerations\n"
"float64[] effort\n"
"duration time_from_start\n"
;
  }

  static const char* value(const ::pr_control_msgs::JointGroupCommandFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pr_control_msgs::JointGroupCommandFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.joint_names);
      stream.next(m.desired);
      stream.next(m.actual);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointGroupCommandFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pr_control_msgs::JointGroupCommandFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pr_control_msgs::JointGroupCommandFeedback_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "joint_names[]" << std::endl;
    for (size_t i = 0; i < v.joint_names.size(); ++i)
    {
      s << indent << "  joint_names[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.joint_names[i]);
    }
    s << indent << "desired: ";
    s << std::endl;
    Printer< ::trajectory_msgs::JointTrajectoryPoint_<ContainerAllocator> >::stream(s, indent + "  ", v.desired);
    s << indent << "actual: ";
    s << std::endl;
    Printer< ::trajectory_msgs::JointTrajectoryPoint_<ContainerAllocator> >::stream(s, indent + "  ", v.actual);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PR_CONTROL_MSGS_MESSAGE_JOINTGROUPCOMMANDFEEDBACK_H
