; Auto-generated. Do not edit!


(cl:in-package pr_control_msgs-msg)


;//! \htmlinclude TriggerGoal.msg.html

(cl:defclass <TriggerGoal> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass TriggerGoal (<TriggerGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TriggerGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TriggerGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name pr_control_msgs-msg:<TriggerGoal> is deprecated: use pr_control_msgs-msg:TriggerGoal instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TriggerGoal>) ostream)
  "Serializes a message object of type '<TriggerGoal>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TriggerGoal>) istream)
  "Deserializes a message object of type '<TriggerGoal>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TriggerGoal>)))
  "Returns string type for a message object of type '<TriggerGoal>"
  "pr_control_msgs/TriggerGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TriggerGoal)))
  "Returns string type for a message object of type 'TriggerGoal"
  "pr_control_msgs/TriggerGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TriggerGoal>)))
  "Returns md5sum for a message object of type '<TriggerGoal>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TriggerGoal)))
  "Returns md5sum for a message object of type 'TriggerGoal"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TriggerGoal>)))
  "Returns full string definition for message of type '<TriggerGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# no goal~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TriggerGoal)))
  "Returns full string definition for message of type 'TriggerGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# no goal~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TriggerGoal>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TriggerGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'TriggerGoal
))
