// Generated by gencpp from file yui_bathing/PatchProcessor.msg
// DO NOT EDIT!


#ifndef YUI_BATHING_MESSAGE_PATCHPROCESSOR_H
#define YUI_BATHING_MESSAGE_PATCHPROCESSOR_H

#include <ros/service_traits.h>


#include <yui_bathing/PatchProcessorRequest.h>
#include <yui_bathing/PatchProcessorResponse.h>


namespace yui_bathing
{

struct PatchProcessor
{

typedef PatchProcessorRequest Request;
typedef PatchProcessorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PatchProcessor
} // namespace yui_bathing


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::yui_bathing::PatchProcessor > {
  static const char* value()
  {
    return "925376cec6effbc61eea0d6363975189";
  }

  static const char* value(const ::yui_bathing::PatchProcessor&) { return value(); }
};

template<>
struct DataType< ::yui_bathing::PatchProcessor > {
  static const char* value()
  {
    return "yui_bathing/PatchProcessor";
  }

  static const char* value(const ::yui_bathing::PatchProcessor&) { return value(); }
};


// service_traits::MD5Sum< ::yui_bathing::PatchProcessorRequest> should match
// service_traits::MD5Sum< ::yui_bathing::PatchProcessor >
template<>
struct MD5Sum< ::yui_bathing::PatchProcessorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::yui_bathing::PatchProcessor >::value();
  }
  static const char* value(const ::yui_bathing::PatchProcessorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::yui_bathing::PatchProcessorRequest> should match
// service_traits::DataType< ::yui_bathing::PatchProcessor >
template<>
struct DataType< ::yui_bathing::PatchProcessorRequest>
{
  static const char* value()
  {
    return DataType< ::yui_bathing::PatchProcessor >::value();
  }
  static const char* value(const ::yui_bathing::PatchProcessorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::yui_bathing::PatchProcessorResponse> should match
// service_traits::MD5Sum< ::yui_bathing::PatchProcessor >
template<>
struct MD5Sum< ::yui_bathing::PatchProcessorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::yui_bathing::PatchProcessor >::value();
  }
  static const char* value(const ::yui_bathing::PatchProcessorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::yui_bathing::PatchProcessorResponse> should match
// service_traits::DataType< ::yui_bathing::PatchProcessor >
template<>
struct DataType< ::yui_bathing::PatchProcessorResponse>
{
  static const char* value()
  {
    return DataType< ::yui_bathing::PatchProcessor >::value();
  }
  static const char* value(const ::yui_bathing::PatchProcessorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // YUI_BATHING_MESSAGE_PATCHPROCESSOR_H
