// Auto-generated. Do not edit!

// (in-package pr_control_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let JointGroupCommandActionGoal = require('./JointGroupCommandActionGoal.js');
let JointGroupCommandActionResult = require('./JointGroupCommandActionResult.js');
let JointGroupCommandActionFeedback = require('./JointGroupCommandActionFeedback.js');

//-----------------------------------------------------------

class JointGroupCommandAction {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.action_goal = null;
      this.action_result = null;
      this.action_feedback = null;
    }
    else {
      if (initObj.hasOwnProperty('action_goal')) {
        this.action_goal = initObj.action_goal
      }
      else {
        this.action_goal = new JointGroupCommandActionGoal();
      }
      if (initObj.hasOwnProperty('action_result')) {
        this.action_result = initObj.action_result
      }
      else {
        this.action_result = new JointGroupCommandActionResult();
      }
      if (initObj.hasOwnProperty('action_feedback')) {
        this.action_feedback = initObj.action_feedback
      }
      else {
        this.action_feedback = new JointGroupCommandActionFeedback();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type JointGroupCommandAction
    // Serialize message field [action_goal]
    bufferOffset = JointGroupCommandActionGoal.serialize(obj.action_goal, buffer, bufferOffset);
    // Serialize message field [action_result]
    bufferOffset = JointGroupCommandActionResult.serialize(obj.action_result, buffer, bufferOffset);
    // Serialize message field [action_feedback]
    bufferOffset = JointGroupCommandActionFeedback.serialize(obj.action_feedback, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type JointGroupCommandAction
    let len;
    let data = new JointGroupCommandAction(null);
    // Deserialize message field [action_goal]
    data.action_goal = JointGroupCommandActionGoal.deserialize(buffer, bufferOffset);
    // Deserialize message field [action_result]
    data.action_result = JointGroupCommandActionResult.deserialize(buffer, bufferOffset);
    // Deserialize message field [action_feedback]
    data.action_feedback = JointGroupCommandActionFeedback.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += JointGroupCommandActionGoal.getMessageSize(object.action_goal);
    length += JointGroupCommandActionResult.getMessageSize(object.action_result);
    length += JointGroupCommandActionFeedback.getMessageSize(object.action_feedback);
    return length;
  }

  static datatype() {
    // Returns string type for a message object
    return 'pr_control_msgs/JointGroupCommandAction';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '8cf077f56d8a79df879989a10892e055';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    JointGroupCommandActionGoal action_goal
    JointGroupCommandActionResult action_result
    JointGroupCommandActionFeedback action_feedback
    
    ================================================================================
    MSG: pr_control_msgs/JointGroupCommandActionGoal
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    Header header
    actionlib_msgs/GoalID goal_id
    JointGroupCommandGoal goal
    
    ================================================================================
    MSG: std_msgs/Header
    # Standard metadata for higher-level stamped data types.
    # This is generally used to communicate timestamped data 
    # in a particular coordinate frame.
    # 
    # sequence ID: consecutively increasing ID 
    uint32 seq
    #Two-integer timestamp that is expressed as:
    # * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
    # * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
    # time-handling sugar is provided by the client library
    time stamp
    #Frame this data is associated with
    string frame_id
    
    ================================================================================
    MSG: actionlib_msgs/GoalID
    # The stamp should store the time at which this goal was requested.
    # It is used by an action server when it tries to preempt all
    # goals that were requested before a certain time
    time stamp
    
    # The id provides a way to associate feedback and
    # result message with specific goal requests. The id
    # specified must be unique.
    string id
    
    
    ================================================================================
    MSG: pr_control_msgs/JointGroupCommandGoal
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Used in time-stamping the goal.
    Header header
    
    # Name list of the joints. You don't need to specify all joints of the
    # robot. Joint names are case-sensitive.
    string[] joint_names
    
    # A command to the joints listed in joint_names.
    # Can be position, velocity, effort, and/or acceleration.
    # The order must be identical.
    # time_from_start is the command duration / timeout
    # Set to 0 for no timeout.
    trajectory_msgs/JointTrajectoryPoint command
    
    
    ================================================================================
    MSG: trajectory_msgs/JointTrajectoryPoint
    # Each trajectory point specifies either positions[, velocities[, accelerations]]
    # or positions[, effort] for the trajectory to be executed.
    # All specified values are in the same order as the joint names in JointTrajectory.msg
    
    float64[] positions
    float64[] velocities
    float64[] accelerations
    float64[] effort
    duration time_from_start
    
    ================================================================================
    MSG: pr_control_msgs/JointGroupCommandActionResult
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    Header header
    actionlib_msgs/GoalStatus status
    JointGroupCommandResult result
    
    ================================================================================
    MSG: actionlib_msgs/GoalStatus
    GoalID goal_id
    uint8 status
    uint8 PENDING         = 0   # The goal has yet to be processed by the action server
    uint8 ACTIVE          = 1   # The goal is currently being processed by the action server
    uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing
                                #   and has since completed its execution (Terminal State)
    uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)
    uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due
                                #    to some failure (Terminal State)
    uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,
                                #    because the goal was unattainable or invalid (Terminal State)
    uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing
                                #    and has not yet completed execution
    uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,
                                #    but the action server has not yet confirmed that the goal is canceled
    uint8 RECALLED        = 8   # The goal received a cancel request before it started executing
                                #    and was successfully cancelled (Terminal State)
    uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be
                                #    sent over the wire by an action server
    
    #Allow for the user to associate a string with GoalStatus for debugging
    string text
    
    
    ================================================================================
    MSG: pr_control_msgs/JointGroupCommandResult
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    int32 error_code
    int32 SUCCESSFUL = 0
    int32 INVALID_GOAL = -1
    int32 INVALID_JOINTS = -2
    int32 OLD_HEADER_TIMESTAMP = -3
    
    # Human readable description of the error code. Contains complementary
    # information that is especially useful when execution fails, for instance:
    # - INVALID_GOAL: The reason for the invalid goal (e.g., the requested
    #   command violates the controller limits).
    # - INVALID_JOINTS: The mismatch between the expected controller joints
    #   and those provided in the goal.
    string error_string
    
    
    ================================================================================
    MSG: pr_control_msgs/JointGroupCommandActionFeedback
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    Header header
    actionlib_msgs/GoalStatus status
    JointGroupCommandFeedback feedback
    
    ================================================================================
    MSG: pr_control_msgs/JointGroupCommandFeedback
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    Header header
    string[] joint_names
    trajectory_msgs/JointTrajectoryPoint desired
    trajectory_msgs/JointTrajectoryPoint actual
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new JointGroupCommandAction(null);
    if (msg.action_goal !== undefined) {
      resolved.action_goal = JointGroupCommandActionGoal.Resolve(msg.action_goal)
    }
    else {
      resolved.action_goal = new JointGroupCommandActionGoal()
    }

    if (msg.action_result !== undefined) {
      resolved.action_result = JointGroupCommandActionResult.Resolve(msg.action_result)
    }
    else {
      resolved.action_result = new JointGroupCommandActionResult()
    }

    if (msg.action_feedback !== undefined) {
      resolved.action_feedback = JointGroupCommandActionFeedback.Resolve(msg.action_feedback)
    }
    else {
      resolved.action_feedback = new JointGroupCommandActionFeedback()
    }

    return resolved;
    }
};

module.exports = JointGroupCommandAction;
