// Auto-generated. Do not edit!

// (in-package pr_control_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let std_msgs = _finder('std_msgs');

//-----------------------------------------------------------

class JointModeCommandGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.header = null;
      this.joint_names = null;
      this.modes = null;
    }
    else {
      if (initObj.hasOwnProperty('header')) {
        this.header = initObj.header
      }
      else {
        this.header = new std_msgs.msg.Header();
      }
      if (initObj.hasOwnProperty('joint_names')) {
        this.joint_names = initObj.joint_names
      }
      else {
        this.joint_names = [];
      }
      if (initObj.hasOwnProperty('modes')) {
        this.modes = initObj.modes
      }
      else {
        this.modes = [];
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type JointModeCommandGoal
    // Serialize message field [header]
    bufferOffset = std_msgs.msg.Header.serialize(obj.header, buffer, bufferOffset);
    // Serialize message field [joint_names]
    bufferOffset = _arraySerializer.string(obj.joint_names, buffer, bufferOffset, null);
    // Serialize message field [modes]
    bufferOffset = _arraySerializer.int32(obj.modes, buffer, bufferOffset, null);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type JointModeCommandGoal
    let len;
    let data = new JointModeCommandGoal(null);
    // Deserialize message field [header]
    data.header = std_msgs.msg.Header.deserialize(buffer, bufferOffset);
    // Deserialize message field [joint_names]
    data.joint_names = _arrayDeserializer.string(buffer, bufferOffset, null)
    // Deserialize message field [modes]
    data.modes = _arrayDeserializer.int32(buffer, bufferOffset, null)
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += std_msgs.msg.Header.getMessageSize(object.header);
    object.joint_names.forEach((val) => {
      length += 4 + _getByteLength(val);
    });
    length += 4 * object.modes.length;
    return length + 8;
  }

  static datatype() {
    // Returns string type for a message object
    return 'pr_control_msgs/JointModeCommandGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'd85807739613da1122af407e58165361';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Used in time-stamping the goal.
    Header header
    
    # Name list of the joints. You don't need to specify all joints of the
    # robot. Joint names are case-sensitive.
    string[] joint_names
    
    # Mode command to the joints listed in joint_names.
    # The order must be identical.
    int32[] modes
    
    int32 BEGIN          = -1
    int32 POSITION       = 0
    int32 VELOCITY       = 1
    int32 EFFORT         = 2
    int32 NOMODE         = 3
    int32 OTHER          = 3
    int32 EMERGENCY_STOP = 4
    int32 SWITCHING      = 5
    int32 ERROR          = 6
    
    ================================================================================
    MSG: std_msgs/Header
    # Standard metadata for higher-level stamped data types.
    # This is generally used to communicate timestamped data 
    # in a particular coordinate frame.
    # 
    # sequence ID: consecutively increasing ID 
    uint32 seq
    #Two-integer timestamp that is expressed as:
    # * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
    # * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
    # time-handling sugar is provided by the client library
    time stamp
    #Frame this data is associated with
    string frame_id
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new JointModeCommandGoal(null);
    if (msg.header !== undefined) {
      resolved.header = std_msgs.msg.Header.Resolve(msg.header)
    }
    else {
      resolved.header = new std_msgs.msg.Header()
    }

    if (msg.joint_names !== undefined) {
      resolved.joint_names = msg.joint_names;
    }
    else {
      resolved.joint_names = []
    }

    if (msg.modes !== undefined) {
      resolved.modes = msg.modes;
    }
    else {
      resolved.modes = []
    }

    return resolved;
    }
};

// Constants for message
JointModeCommandGoal.Constants = {
  BEGIN: -1,
  POSITION: 0,
  VELOCITY: 1,
  EFFORT: 2,
  NOMODE: 3,
  OTHER: 3,
  EMERGENCY_STOP: 4,
  SWITCHING: 5,
  ERROR: 6,
}

module.exports = JointModeCommandGoal;
