// Auto-generated. Do not edit!

// (in-package pr_control_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class SetForceTorqueThresholdGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.force_threshold = null;
      this.torque_threshold = null;
      this.retare = null;
    }
    else {
      if (initObj.hasOwnProperty('force_threshold')) {
        this.force_threshold = initObj.force_threshold
      }
      else {
        this.force_threshold = 0.0;
      }
      if (initObj.hasOwnProperty('torque_threshold')) {
        this.torque_threshold = initObj.torque_threshold
      }
      else {
        this.torque_threshold = 0.0;
      }
      if (initObj.hasOwnProperty('retare')) {
        this.retare = initObj.retare
      }
      else {
        this.retare = false;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type SetForceTorqueThresholdGoal
    // Serialize message field [force_threshold]
    bufferOffset = _serializer.float64(obj.force_threshold, buffer, bufferOffset);
    // Serialize message field [torque_threshold]
    bufferOffset = _serializer.float64(obj.torque_threshold, buffer, bufferOffset);
    // Serialize message field [retare]
    bufferOffset = _serializer.bool(obj.retare, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type SetForceTorqueThresholdGoal
    let len;
    let data = new SetForceTorqueThresholdGoal(null);
    // Deserialize message field [force_threshold]
    data.force_threshold = _deserializer.float64(buffer, bufferOffset);
    // Deserialize message field [torque_threshold]
    data.torque_threshold = _deserializer.float64(buffer, bufferOffset);
    // Deserialize message field [retare]
    data.retare = _deserializer.bool(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 17;
  }

  static datatype() {
    // Returns string type for a message object
    return 'pr_control_msgs/SetForceTorqueThresholdGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'e5d09cefad81aea029dbb143ca87e1e5';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    float64 force_threshold
    float64 torque_threshold
    bool retare
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new SetForceTorqueThresholdGoal(null);
    if (msg.force_threshold !== undefined) {
      resolved.force_threshold = msg.force_threshold;
    }
    else {
      resolved.force_threshold = 0.0
    }

    if (msg.torque_threshold !== undefined) {
      resolved.torque_threshold = msg.torque_threshold;
    }
    else {
      resolved.torque_threshold = 0.0
    }

    if (msg.retare !== undefined) {
      resolved.retare = msg.retare;
    }
    else {
      resolved.retare = false
    }

    return resolved;
    }
};

module.exports = SetForceTorqueThresholdGoal;
