// Generated by gencpp from file pr_control_msgs/JointGroupCommandResult.msg
// DO NOT EDIT!


#ifndef PR_CONTROL_MSGS_MESSAGE_JOINTGROUPCOMMANDRESULT_H
#define PR_CONTROL_MSGS_MESSAGE_JOINTGROUPCOMMANDRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pr_control_msgs
{
template <class ContainerAllocator>
struct JointGroupCommandResult_
{
  typedef JointGroupCommandResult_<ContainerAllocator> Type;

  JointGroupCommandResult_()
    : error_code(0)
    , error_string()  {
    }
  JointGroupCommandResult_(const ContainerAllocator& _alloc)
    : error_code(0)
    , error_string(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _error_code_type;
  _error_code_type error_code;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _error_string_type;
  _error_string_type error_string;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(SUCCESSFUL)
  #undef SUCCESSFUL
#endif
#if defined(_WIN32) && defined(INVALID_GOAL)
  #undef INVALID_GOAL
#endif
#if defined(_WIN32) && defined(INVALID_JOINTS)
  #undef INVALID_JOINTS
#endif
#if defined(_WIN32) && defined(OLD_HEADER_TIMESTAMP)
  #undef OLD_HEADER_TIMESTAMP
#endif

  enum {
    SUCCESSFUL = 0,
    INVALID_GOAL = -1,
    INVALID_JOINTS = -2,
    OLD_HEADER_TIMESTAMP = -3,
  };


  typedef boost::shared_ptr< ::pr_control_msgs::JointGroupCommandResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pr_control_msgs::JointGroupCommandResult_<ContainerAllocator> const> ConstPtr;

}; // struct JointGroupCommandResult_

typedef ::pr_control_msgs::JointGroupCommandResult_<std::allocator<void> > JointGroupCommandResult;

typedef boost::shared_ptr< ::pr_control_msgs::JointGroupCommandResult > JointGroupCommandResultPtr;
typedef boost::shared_ptr< ::pr_control_msgs::JointGroupCommandResult const> JointGroupCommandResultConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pr_control_msgs::JointGroupCommandResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pr_control_msgs::JointGroupCommandResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pr_control_msgs::JointGroupCommandResult_<ContainerAllocator1> & lhs, const ::pr_control_msgs::JointGroupCommandResult_<ContainerAllocator2> & rhs)
{
  return lhs.error_code == rhs.error_code &&
    lhs.error_string == rhs.error_string;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pr_control_msgs::JointGroupCommandResult_<ContainerAllocator1> & lhs, const ::pr_control_msgs::JointGroupCommandResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pr_control_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pr_control_msgs::JointGroupCommandResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pr_control_msgs::JointGroupCommandResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pr_control_msgs::JointGroupCommandResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pr_control_msgs::JointGroupCommandResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pr_control_msgs::JointGroupCommandResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pr_control_msgs::JointGroupCommandResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pr_control_msgs::JointGroupCommandResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "163c90cc66958823fc0b619077c84273";
  }

  static const char* value(const ::pr_control_msgs::JointGroupCommandResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x163c90cc66958823ULL;
  static const uint64_t static_value2 = 0xfc0b619077c84273ULL;
};

template<class ContainerAllocator>
struct DataType< ::pr_control_msgs::JointGroupCommandResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pr_control_msgs/JointGroupCommandResult";
  }

  static const char* value(const ::pr_control_msgs::JointGroupCommandResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pr_control_msgs::JointGroupCommandResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"int32 error_code\n"
"int32 SUCCESSFUL = 0\n"
"int32 INVALID_GOAL = -1\n"
"int32 INVALID_JOINTS = -2\n"
"int32 OLD_HEADER_TIMESTAMP = -3\n"
"\n"
"# Human readable description of the error code. Contains complementary\n"
"# information that is especially useful when execution fails, for instance:\n"
"# - INVALID_GOAL: The reason for the invalid goal (e.g., the requested\n"
"#   command violates the controller limits).\n"
"# - INVALID_JOINTS: The mismatch between the expected controller joints\n"
"#   and those provided in the goal.\n"
"string error_string\n"
"\n"
;
  }

  static const char* value(const ::pr_control_msgs::JointGroupCommandResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pr_control_msgs::JointGroupCommandResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.error_code);
      stream.next(m.error_string);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointGroupCommandResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pr_control_msgs::JointGroupCommandResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pr_control_msgs::JointGroupCommandResult_<ContainerAllocator>& v)
  {
    s << indent << "error_code: ";
    Printer<int32_t>::stream(s, indent + "  ", v.error_code);
    s << indent << "error_string: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.error_string);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PR_CONTROL_MSGS_MESSAGE_JOINTGROUPCOMMANDRESULT_H
