// Generated by gencpp from file pr_control_msgs/JointModeCommandGoal.msg
// DO NOT EDIT!


#ifndef PR_CONTROL_MSGS_MESSAGE_JOINTMODECOMMANDGOAL_H
#define PR_CONTROL_MSGS_MESSAGE_JOINTMODECOMMANDGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace pr_control_msgs
{
template <class ContainerAllocator>
struct JointModeCommandGoal_
{
  typedef JointModeCommandGoal_<ContainerAllocator> Type;

  JointModeCommandGoal_()
    : header()
    , joint_names()
    , modes()  {
    }
  JointModeCommandGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , joint_names(_alloc)
    , modes(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _joint_names_type;
  _joint_names_type joint_names;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _modes_type;
  _modes_type modes;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(BEGIN)
  #undef BEGIN
#endif
#if defined(_WIN32) && defined(POSITION)
  #undef POSITION
#endif
#if defined(_WIN32) && defined(VELOCITY)
  #undef VELOCITY
#endif
#if defined(_WIN32) && defined(EFFORT)
  #undef EFFORT
#endif
#if defined(_WIN32) && defined(NOMODE)
  #undef NOMODE
#endif
#if defined(_WIN32) && defined(OTHER)
  #undef OTHER
#endif
#if defined(_WIN32) && defined(EMERGENCY_STOP)
  #undef EMERGENCY_STOP
#endif
#if defined(_WIN32) && defined(SWITCHING)
  #undef SWITCHING
#endif
#if defined(_WIN32) && defined(ERROR)
  #undef ERROR
#endif

  enum {
    BEGIN = -1,
    POSITION = 0,
    VELOCITY = 1,
    EFFORT = 2,
    NOMODE = 3,
    OTHER = 3,
    EMERGENCY_STOP = 4,
    SWITCHING = 5,
    ERROR = 6,
  };


  typedef boost::shared_ptr< ::pr_control_msgs::JointModeCommandGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pr_control_msgs::JointModeCommandGoal_<ContainerAllocator> const> ConstPtr;

}; // struct JointModeCommandGoal_

typedef ::pr_control_msgs::JointModeCommandGoal_<std::allocator<void> > JointModeCommandGoal;

typedef boost::shared_ptr< ::pr_control_msgs::JointModeCommandGoal > JointModeCommandGoalPtr;
typedef boost::shared_ptr< ::pr_control_msgs::JointModeCommandGoal const> JointModeCommandGoalConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pr_control_msgs::JointModeCommandGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pr_control_msgs::JointModeCommandGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pr_control_msgs::JointModeCommandGoal_<ContainerAllocator1> & lhs, const ::pr_control_msgs::JointModeCommandGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.joint_names == rhs.joint_names &&
    lhs.modes == rhs.modes;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pr_control_msgs::JointModeCommandGoal_<ContainerAllocator1> & lhs, const ::pr_control_msgs::JointModeCommandGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pr_control_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pr_control_msgs::JointModeCommandGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pr_control_msgs::JointModeCommandGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pr_control_msgs::JointModeCommandGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pr_control_msgs::JointModeCommandGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pr_control_msgs::JointModeCommandGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pr_control_msgs::JointModeCommandGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pr_control_msgs::JointModeCommandGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d85807739613da1122af407e58165361";
  }

  static const char* value(const ::pr_control_msgs::JointModeCommandGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd85807739613da11ULL;
  static const uint64_t static_value2 = 0x22af407e58165361ULL;
};

template<class ContainerAllocator>
struct DataType< ::pr_control_msgs::JointModeCommandGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pr_control_msgs/JointModeCommandGoal";
  }

  static const char* value(const ::pr_control_msgs::JointModeCommandGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pr_control_msgs::JointModeCommandGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Used in time-stamping the goal.\n"
"Header header\n"
"\n"
"# Name list of the joints. You don't need to specify all joints of the\n"
"# robot. Joint names are case-sensitive.\n"
"string[] joint_names\n"
"\n"
"# Mode command to the joints listed in joint_names.\n"
"# The order must be identical.\n"
"int32[] modes\n"
"\n"
"int32 BEGIN          = -1\n"
"int32 POSITION       = 0\n"
"int32 VELOCITY       = 1\n"
"int32 EFFORT         = 2\n"
"int32 NOMODE         = 3\n"
"int32 OTHER          = 3\n"
"int32 EMERGENCY_STOP = 4\n"
"int32 SWITCHING      = 5\n"
"int32 ERROR          = 6\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::pr_control_msgs::JointModeCommandGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pr_control_msgs::JointModeCommandGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.joint_names);
      stream.next(m.modes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointModeCommandGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pr_control_msgs::JointModeCommandGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pr_control_msgs::JointModeCommandGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "joint_names[]" << std::endl;
    for (size_t i = 0; i < v.joint_names.size(); ++i)
    {
      s << indent << "  joint_names[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.joint_names[i]);
    }
    s << indent << "modes[]" << std::endl;
    for (size_t i = 0; i < v.modes.size(); ++i)
    {
      s << indent << "  modes[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.modes[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PR_CONTROL_MSGS_MESSAGE_JOINTMODECOMMANDGOAL_H
