// Generated by gencpp from file pr_control_msgs/SetPositionFeedback.msg
// DO NOT EDIT!


#ifndef PR_CONTROL_MSGS_MESSAGE_SETPOSITIONFEEDBACK_H
#define PR_CONTROL_MSGS_MESSAGE_SETPOSITIONFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pr_control_msgs
{
template <class ContainerAllocator>
struct SetPositionFeedback_
{
  typedef SetPositionFeedback_<ContainerAllocator> Type;

  SetPositionFeedback_()
    {
    }
  SetPositionFeedback_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::pr_control_msgs::SetPositionFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pr_control_msgs::SetPositionFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct SetPositionFeedback_

typedef ::pr_control_msgs::SetPositionFeedback_<std::allocator<void> > SetPositionFeedback;

typedef boost::shared_ptr< ::pr_control_msgs::SetPositionFeedback > SetPositionFeedbackPtr;
typedef boost::shared_ptr< ::pr_control_msgs::SetPositionFeedback const> SetPositionFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pr_control_msgs::SetPositionFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pr_control_msgs::SetPositionFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace pr_control_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pr_control_msgs::SetPositionFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pr_control_msgs::SetPositionFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pr_control_msgs::SetPositionFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pr_control_msgs::SetPositionFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pr_control_msgs::SetPositionFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pr_control_msgs::SetPositionFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pr_control_msgs::SetPositionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::pr_control_msgs::SetPositionFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::pr_control_msgs::SetPositionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pr_control_msgs/SetPositionFeedback";
  }

  static const char* value(const ::pr_control_msgs::SetPositionFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pr_control_msgs::SetPositionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# no feedback\n"
"\n"
;
  }

  static const char* value(const ::pr_control_msgs::SetPositionFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pr_control_msgs::SetPositionFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetPositionFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pr_control_msgs::SetPositionFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::pr_control_msgs::SetPositionFeedback_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // PR_CONTROL_MSGS_MESSAGE_SETPOSITIONFEEDBACK_H
